// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm7ExqGpois3YpIvXyNc8a6FAPMyIS-ns',
    appId: '1:549297858196:web:777b23e40f148dd57df681',
    messagingSenderId: '549297858196',
    projectId: 'flutterauth-9b968',
    authDomain: 'flutterauth-9b968.firebaseapp.com',
    storageBucket: 'flutterauth-9b968.appspot.com',
    measurementId: 'G-JEV7STHKX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB23iyfmqeUoKkY-Soz6KonMqpBSoKAGjQ',
    appId: '1:549297858196:android:44aa126a1118e3567df681',
    messagingSenderId: '549297858196',
    projectId: 'flutterauth-9b968',
    storageBucket: 'flutterauth-9b968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgv1TQZfyX3CjtPD_NbyBp-aaxL9EcSuY',
    appId: '1:549297858196:ios:de057a29db230a0b7df681',
    messagingSenderId: '549297858196',
    projectId: 'flutterauth-9b968',
    storageBucket: 'flutterauth-9b968.appspot.com',
    iosBundleId: 'com.example.widgetsBasic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgv1TQZfyX3CjtPD_NbyBp-aaxL9EcSuY',
    appId: '1:549297858196:ios:2b4520bb9e1d33e67df681',
    messagingSenderId: '549297858196',
    projectId: 'flutterauth-9b968',
    storageBucket: 'flutterauth-9b968.appspot.com',
    iosBundleId: 'com.example.widgetsBasic.RunnerTests',
  );
}
